name: rest_api
description: Rest Api tutorial

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  email_validator: ^2.0.1
  page_transition: ^2.0.5
  fluttertoast: ^8.0.9
  get: ^4.6.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
